version: "2"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: fmiselli:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: develop
    upstream: fmiselli:develop        # Required. Can be a branch in the same forked repo.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.    
